using CleanBrilliantCompany.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace CleanBrilliantCompany.ReportManagement.Services
{
    public class ReportGenerator
    {
        public byte[] GeneratePDF(Report report)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(50);
                    page.Size(PageSizes.A4);
                    page.DefaultTextStyle(x => x.FontSize(12));

                    page.Header().Text($"Report: {report.ReportName}").Bold().FontSize(20);
                    page.Content().Column(col =>
                    {
                        col.Item().Text($"Type: {report.ReportType}").Italic();
                        col.Item().PaddingTop(10).Text("Generated by AI Report System");

                        if (!string.IsNullOrWhiteSpace(report.ReportDataText))
                        {
                            col.Item().PaddingTop(20).Text("Summary:").Bold();
                            col.Item().PaddingTop(5).Text(report.ReportDataText);  //  Make sure this is the AI text
                        }
                        else
                        {
                            col.Item().PaddingTop(20).Text("⚠ No content was generated by the AI.");
                        }
                    });
                });
            });

            using var stream = new MemoryStream();
            document.GeneratePdf(stream);
            return stream.ToArray();
        }
    }
}
