using CleanBrilliantCompany.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace CleanBrilliantCompany.Services
{
    public class ReportGenerator
    {
        public byte[] GeneratePDF(Report report)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Header().Text($"Report: {report.ReportName}").FontSize(20).Bold();
                    page.Content().Text($"Type: {report.ReportType}");
                    page.Footer().Text("Generated by AI Report System");
                });
            });

            return document.GeneratePdf();
        }
    }
}
